name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * 0'
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: "${{github.repository}}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: mkcert
    - name: Setup mkcert
      env:
        MKCERT_VERSION: v1.4.3
      run: |
        set -x
        curl https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64 --location --output /tmp/mkcert
        chmod 744 /tmp/mkcert
        sudo mv /tmp/mkcert /bin/mkcert
        mkcert -install
    - name: Create signed TLS certificates for localhost
      run: |
        mkcert -cert-file tests/localhost.crt -key-file tests/localhost.key localhost 0.0.0.0 ::1
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: tlan16/nginx
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
    - uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKER_USERNAME }}/nginx
        short-description: 'nginx with QUIC, HTTP3, brotli, njs module and Grade A+ SSL'
        readme-filepath: 'readme.md'
    - uses: gautamkrishnar/keepalive-workflow@v1
