name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * 0'
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{github.repository}}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: mkcert
    - name: Setup mkcert
      env:
        MKCERT_VERSION: v1.4.3
      run: |
        set -x
        curl https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64 --location --output /tmp/mkcert
        chmod 744 /tmp/mkcert
        sudo mv /tmp/mkcert /bin/mkcert
        mkcert -install
    - name: Create signed TLS certificates for localhost
      run: |
        mkcert -cert-file tests/localhost.crt -key-file tests/localhost.key localhost 0.0.0.0 ::1
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/cache@v4
      id: cache
      with:
        path: cache-mount
        key: cache-mount-${{ hashFiles('Dockerfile') }}

    - uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        builder: ${{ steps.setup-buildx.outputs.name }}
        cache-dir: cache-mount
        dockerfile: Dockerfile
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: tlan16/nginx
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
